server:
  port: 9000
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Dipayan-Das1/cloud-config-repository
          searchPaths: '{application}'
          username: GIT_USERNAME
          password: GIT_PASSWORD
