### This is the main way to configure the application (other than annotations).
### This fils is in Yaml format but you can also do this using the traditional
### Java properties file.


spring.datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:bootexample;MODE=MySQL

#todo: make sure to always enable security in production
security:
  basic:
    enabled: false

management:
  security:
    enabled: false
  endpoint:
    health:
      show-details: "ALWAYS"


#default project info followed by actual injected pom-specified values.
project:
  name: spring-boot-person-service
  version: 0.1
  description: spring-boot-person-service
info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}

user.service:
  name: 'default profile:'
---
spring:
  profiles: test

spring.jpa:
    hibernate.ddl-auto: create-drop

user.service:
  name: 'test profile:'