### This is the main way to configure the application (other than annotations).
### This fils is in Yaml format but you can also do this using the traditional
### Java properties file.

spring:
  profile:
    active:
      dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

---
spring:
  profiles: test

spring.jpa:
    hibernate.ddl-auto: create-drop

user.service:
  name: 'test profile:'